version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    # Only keep one dependency update PR open at a time
    open-pull-requests-limit: 1

    labels:
      - "dependencies"

    commit-message:
      prefix: "deps"
