name: React CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build